clear
echo "Test of the scale range block"
echo ""
echo ""
echo "Make a post block"
curl "localhost:7070/create?blockType=postto"
echo ""
echo ""
echo "Make a scale block"
curl "localhost:7070/create?blockType=scale_range"
echo ""
echo ""
echo "Set a rule for the block"
curl "localhost:7070/blocks/2/set_rule" --data '{"Key":"test", "Min":"min", "Max":"max"}'
echo ""
echo ""
echo "Connect the postto and sd blocks"
curl "localhost:7070/connect?from=1&to=2"
echo ""
echo ""
echo "Send data to the block"
curl "localhost:7070/blocks/1/in" --data '{"test":1.0, "min":-1, "max":1}'
echo ""
echo ""
echo "Get the state of the block"
curl "localhost:7070/blocks/2/x_scaled"
echo ""
echo ""
echo "Send data to the block"
curl "localhost:7070/blocks/1/in" --data '{"test":2.0, "min":-1, "max":1}'
echo ""
echo ""
echo "Get of the state of the block again"
curl "localhost:7070/blocks/2/x_scaled"
echo ""
echo ""
echo "Send data to the block"
curl "localhost:7070/blocks/1/in" --data '{"test":3.0, "min":-1, "max":1}'
echo ""
echo ""
echo "Get of the state of the block again"
curl "localhost:7070/blocks/2/x_scaled"
echo ""
echo ""
